name: 'Changelog Action'
description: 'Generate basic changelog from commits'
author: 'FloWide'
inputs: 
  from-tag:
    description: 'Tag to generate from'
    default: ''
    required: false
  to-tag:
    description: 'Tag to generate to'
    default: ''
    required: false
outputs:
  changelog:
    description: 'Markdown changelog from commits'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    FROM_TAG: ${{inputs.from-tag}}
    TO_TAG: ${{inputs.to-tag}}
